changes paths for use with devcontainer

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,13 +1,13 @@
 #! /bin/bash
 
-defsfile="./Makefile.defs"
+defsfile="/lime/Makefile.defs"
 
 [ -e $defsfile ] && rm $defsfile
 touch $defsfile
 
-echo "LIB_QHULL = qhull" >> $defsfile
+echo "LIB_QHULL = qhullstatic" >> $defsfile
 
-qhull_incs=( "/usr/include/libqhull" "/usr/include/qhull" "/opt/local/include/qhull" "/sw/include/qhull" )
+qhull_incs=( "/usr/include/libqhull" "/usr/include/qhull" "/opt/local/include/qhull" )
 
 for incdir in ${qhull_incs[@]}
 do
@@ -16,9 +16,9 @@ do
     echo "CCFLAGS += -I$incdir" >> $defsfile
     break
   fi
-done 
+done
 
-fitsio_incs=( "/usr/include/cfitsio" "/usr/include/libcfitsio0" )
+fitsio_incs=( "/usr/include" "/usr/include/cfitsio" "/usr/include/libcfitsio0" )
 
 for incdir in ${fitsio_incs[@]}
 do
@@ -27,14 +27,25 @@ do
     echo "CCFLAGS += -I$incdir" >> $defsfile
     break
   fi
-done 
+done
+
+hdf5_incs=( "/usr/include/hdf5/serial" "/usr/include/hdf5" )
+
+for incdir in ${hdf5_incs[@]}; do
+    if [ -e $incdir/hdf5.h ]; then
+        echo "CCFLAGS += -I$incdir" >> $defsfile
+    fi
+done
+
 
 pybin="python"
 pyconf="$pybin-config"
-command -v $pyconf >/dev/null 2>&1 || ! echo "oops" || exit 3
+command -v $pyconf >/dev/null 2>&1 \
+    || ! echo "python-config not found!" \
+    || exit 3
 
 PYCCFLAGS=`$pyconf --cflags`
-PYLDFLAGS=`$pyconf --ldflags`
+PYLDFLAGS=`$pyconf --ldflags --embed`
 echo "PYCCFLAGS = $PYCCFLAGS" >> $defsfile
 echo "PYLDFLAGS = $PYLDFLAGS" >> $defsfile
 
